// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var LoginPassword$ReactTemplate = require("./LoginPassword.bs.js");
var LoginUsername$ReactTemplate = require("./LoginUsername.bs.js");

var component = ReasonReact.statelessComponent("Login");

function handleClick(_, _$1) {
  console.log("clicked!");
  return /* () */0;
}

function make(username, password, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, React.createElement("h1", undefined, "Log in"), React.createElement("div", undefined, ReasonReact.element(/* Some */[username], /* None */0, LoginUsername$ReactTemplate.make(username, /* array */[]))), React.createElement("div", undefined, ReasonReact.element(/* Some */[password], /* None */0, LoginPassword$ReactTemplate.make(password, /* array */[]))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.handleClick = handleClick;
exports.make = make;
/* component Not a pure module */
